# survive edit
name: Scrape News Bot (hourly)

on:
  schedule:
    - cron: '0 * * * *'  # every hour on the hour
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      KEYWORDS: ${{ secrets.KEYWORDS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python hourly_news_scraper.py --since-hours 1.5

      - name: Set timestamp
        id: set_time
        run: echo "timestamp=$(date +'%Y%m%dT%H%M')" >> $GITHUB_OUTPUT

      - name: Upload JSON files as timestamped artifact
        uses: actions/upload-artifact@v4
        with:
          name: rss-feeds-${{ steps.set_time.outputs.timestamp }}
          path: RSS_FEEDS_*.json
